### PR TITLE
fix: changes are not being pushed to the git repository

### LINKED ISSUE #150: Changes are not being pushed to the git repository
Changes to the files made in the `update-config-for-release` command are being done locally but not being pushed to the git repository.

### PR DESCRIPTION
**Pull request by jacobdotcosta**
Closes #150

### CODE REVIEW

File: src/main/java/dev/snowdrop/release/services/GitService.java [hunk 1]
```diff
@@ -110,16 +110,14 @@ public void commitAndPush(String commitMessage, GitConfig config, FileModifier..
                         final var rmCommand = g.rm();
                         files.forEach(file -> {
                             final var path = file.getAbsolutePath().replace(repository.getAbsolutePath() + "/", "");
-                            if (untracked.contains(path) || statusChanged.contains(path)) {
-                                // only add file to be committed if it's part of the modified set or untracked
-                                LOG.infof("Added %s", path);
-                                addCommand.addFilepattern(path);
-                                hasAdd[0] = true;
-                            }
                             if (removed.contains(path) || missing.contains(path)) {
```
Comment (aureamunoz) [inline src/main/java/dev/snowdrop/release/services/GitService.java:113]: can you add a little comment here please?

**Review by aureamunoz — CHANGES_REQUESTED** [review]

File: src/main/java/dev/snowdrop/release/services/GitService.java (hunk 1 above)
Comment (jacobdotcosta) [reply src/main/java/dev/snowdrop/release/services/GitService.java:113]: done.

**Review by aureamunoz — APPROVED** [review]
LGTM
